import type { AgentManager } from './agent-manager.js';
import type { AgentRegistry } from './agent-registry.js';
import type { AgentLifecycle } from './agent-lifecycle.js';
import type { TaskManager } from './task-manager.js';
import type { TaskRouter } from './task-router.js';
import type { SessionManager } from './session-manager.js';
import type { DelegationOrchestrator } from './delegation-orchestrator.js';
import type { PermissionCoordinator } from './permission-coordinator.js';
import type { AuditRecorder } from './audit-recorder.js';
import type { AgentProgress } from './agent-progress.js';
import type { DaemonBridge } from './daemon-bridge.js';
import type { DelegationManager } from './delegation-manager.js';
import type { FallbackRouter } from './fallback-router.js';
import type { MemoryRuntime } from '../memory/runtime.js';
import type { CapabilityService } from '../evolution/index.js';
import type { TakeoverController } from '../testing/model-takeover.js';
import type { ChannelManager } from '../channels/manager.js';
import type { IPluginRuntimeV2 } from '../contracts/plugins-v2.js';
import type { WorkspaceRouter } from './workspace-router.js';
import type { OrgTreeManager } from '../workspaces/org-tree-manager.js';
import type { TrustManager } from '../workspaces/trust-manager.js';
import type { RuntimeRegistry } from './runtime/runtime-registry.js';
import type { CheckpointService } from './checkpoint-service.js';
import type { SchedulerService } from '../scheduler/scheduler-service.js';
import type { INotificationService, IMemoryLayerService, IWorkspaceContextService, IPluginScopeService, ITemplateService, IAsyncDelegationService, ITeamBuilderService } from '../intelligence/index.js';
import type { AppConfig } from './config.js';
import type { LogLevel } from './observability.js';

export interface ServiceContainer {
  agentManager: AgentManager;
  registry: AgentRegistry;
  agentLifecycle: AgentLifecycle;
  taskManager: TaskManager;
  taskRouter: TaskRouter;
  sessionManager: SessionManager;
  messageRouter: DelegationOrchestrator;
  permissionCoordinator: PermissionCoordinator;
  auditRecorder: AuditRecorder;
  agentProgress: AgentProgress | null;
  daemonBridge: DaemonBridge | null;
  delegationManager: DelegationManager;
  fallbackRouter: FallbackRouter;
  memoryRuntime: MemoryRuntime;
  capabilityService: CapabilityService | null;
  takeoverController: TakeoverController | null;
  channelManager: ChannelManager | null;
  pluginRuntimeV2: IPluginRuntimeV2 | null;
  workspaceRouter: WorkspaceRouter | null;
  orgTreeManager: OrgTreeManager | null;
  trustManager: TrustManager | null;
  runtimeRegistry: RuntimeRegistry | null;
  checkpointService: CheckpointService | null;
  schedulerService: SchedulerService | null;
  notificationService: INotificationService | null;
  memoryLayerService: IMemoryLayerService | null;
  workspaceContextService: IWorkspaceContextService | null;
  pluginScopeService: IPluginScopeService | null;
  templateService: ITemplateService | null;
  asyncDelegationService: IAsyncDelegationService | null;
  teamBuilderService: ITeamBuilderService | null;
  config: AppConfig;
  getLogLevel: () => LogLevel;
  setLogLevel: (level: LogLevel) => void;
  setLogLevelResetTimer: (timer: ReturnType<typeof setTimeout> | null) => void;
  getLogLevelResetTimer: () => ReturnType<typeof setTimeout> | null;
  getDaemonStatus?: () => { connected: boolean; runtimes: string[]; availableSlots: number } | null;
}

